# Generated by Django 3.0 on 2020-04-03 11:14

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithBasket',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь с корзиной',
                'verbose_name_plural': 'Пользователи с корзиной',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authapp.shopuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 11, 14, 13, 14923, tzinfo=utc)),
        ),
    ]
